# EXERCISES FOR: 00. Getting started with TensorFlow: A guide to the fundamentals

## 🛠 00. TensorFlow Fundamentals Exercises

1. Create a vector, scalar, matrix and tensor with values of your choosing using `tf.constant()`.
2. Find the shape, rank and size of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape `[5, 300]`.
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape `[224, 224, 3]`.
7. Find the min and max values of the tensor you created in 6 along the first axis.
8. Created a tensor with random values of shape `[1, 224, 224, 3]` then squeeze it to change the shape to `[224, 224, 3]`.
9. Create a tensor with shape `[10]` using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.

### Preliminary

In [1]:
# Create timestamp
import datetime

print(f"Notebook last run (end-to-end): {datetime.datetime.now()}")

Notebook last run (end-to-end): 2024-08-28 08:10:05.453525


In [2]:
# Import TensorFlow
import os
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import tensorflow as tf
print(tf.__version__) # find the version number (should be 2.x+)

2024-08-28 08:10:05.716725: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-08-28 08:10:05.716764: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-08-28 08:10:05.717425: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered


2.15.0


### Exercises
#### [1,2] Simple tensors

In [3]:
d0 = tf.constant(109)
d1 = tf.constant([15,17])
d2 = tf.constant([
    [11,12],[25,26]
])
d3 = tf.constant([
    [[1,2,3],[4,5,6]],
    [[30,33,36],[55,54,43]],
    [[80,80,82],[99,90,93]],
])
d0,d1,d2,d3

2024-08-28 08:10:06.830872: E external/local_xla/xla/stream_executor/cuda/cuda_driver.cc:274] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error


(<tf.Tensor: shape=(), dtype=int32, numpy=109>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([15, 17], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[11, 12],
        [25, 26]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
 array([[[ 1,  2,  3],
         [ 4,  5,  6]],
 
        [[30, 33, 36],
         [55, 54, 43]],
 
        [[80, 80, 82],
         [99, 90, 93]]], dtype=int32)>)

In [4]:
for d in [d0,d1,d2,d3]:
    print(d.shape,d.ndim)

() 0
(2,) 1
(2, 2) 2
(3, 2, 3) 3


In [5]:
# Alternatives:
import numpy as np
d3alt = tf.constant(np.arange(1,25),shape=(2,3,4))
d3alt, d3alt.ndim

(<tf.Tensor: shape=(2, 3, 4), dtype=int64, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])>,
 3)

#### [3,4,5] Random tensors

In [6]:
rand1 = tf.random.Generator.from_seed(77) # set the seed for reproducibility
rand1 = rand1.uniform(shape=(5, 300)) # create tensor from a normal distribution 
rand2 = tf.random.Generator.from_seed(177) # set the seed for reproducibility
rand2 = rand2.uniform(shape=(5, 300)) # create tensor from a normal distribution 
rand1

<tf.Tensor: shape=(5, 300), dtype=float32, numpy=
array([[0.8393048 , 0.89883757, 0.64980876, ..., 0.40920782, 0.6351969 ,
        0.9512656 ],
       [0.49248278, 0.09101331, 0.01480031, ..., 0.6658218 , 0.02978647,
        0.07853341],
       [0.4606458 , 0.8413516 , 0.241979  , ..., 0.9006287 , 0.5701351 ,
        0.2826221 ],
       [0.11323702, 0.8799312 , 0.47277224, ..., 0.7561674 , 0.70352066,
        0.22680473],
       [0.24423313, 0.39240444, 0.32533252, ..., 0.79047453, 0.44491863,
        0.54460037]], dtype=float32)>

#### [6,7] Random tensors

In [7]:
rand3 = tf.random.Generator.from_seed(77) # set the seed for reproducibility
rand3 = rand3.uniform(shape=(224, 224, 3)) # create tensor from a normal distribution
# Find datatypr, shape, rank and size:
print("Datatype of every element:",rand3.dtype)
print("Shape of tensor:",rand3.shape)
print("Rank of tensor:",rand3.ndim)
print("Size of the tensor:",tf.size(rand3).numpy())

Datatype of every element: <dtype: 'float32'>
Shape of tensor: (224, 224, 3)
Rank of tensor: 3
Size of the tensor: 150528


In [17]:
# Find the min and max values of the tensor along the first axis:
print('Minimum value:',tf.reduce_min(rand3).numpy())
print('Maximum value:',tf.reduce_max(rand3).numpy())
print('Mean value:',tf.reduce_mean(rand3).numpy())
print('Standard deviation:',tf.math.reduce_std(rand3).numpy())
print('Variance:',tf.math.reduce_variance(rand3).numpy())

Minimum value: 4.053116e-06
Maximum value: 0.99998736
Mean value: 0.49965236
Standard deviation: 0.28816858
Variance: 0.08304113


#### [8] Manipulate dimensions

In [22]:
A = tf.random.Generator.from_seed(0) # set the seed for reproducibility
A = A.uniform(shape=(1, 224, 224, 3)) # create tensor from a normal distribution
A[:,:,:,1]

<tf.Tensor: shape=(1, 224, 224), dtype=float32, numpy=
array([[[0.8263413 , 0.78749514, 0.99216926, ..., 0.976676  ,
         0.7011992 , 0.7536833 ],
        [0.0927937 , 0.1318667 , 0.29916108, ..., 0.3771491 ,
         0.69211054, 0.48166   ],
        [0.45162737, 0.6775023 , 0.17450547, ..., 0.16113937,
         0.48929954, 0.8036673 ],
        ...,
        [0.3706571 , 0.21750414, 0.31340492, ..., 0.54289234,
         0.0091573 , 0.66913784],
        [0.88771296, 0.49446368, 0.23971832, ..., 0.18161333,
         0.57436764, 0.0412488 ],
        [0.24799585, 0.206483  , 0.11487484, ..., 0.1263851 ,
         0.2772559 , 0.01739931]]], dtype=float32)>

In [25]:
# Squeeze tensor:
A_squeezed = tf.squeeze(A)
A.shape, A_squeezed.shape

(TensorShape([1, 224, 224, 3]), TensorShape([224, 224, 3]))

#### [9,10] One-hot encoding

In [55]:
# Set seeds:
tf.random.set_seed(0), np.random.seed(0)
# Create random tensor:
B = tf.constant(np.random.randint(0, 10, 10))
B

<tf.Tensor: shape=(10,), dtype=int64, numpy=array([5, 0, 3, 3, 7, 9, 3, 5, 2, 4])>

In [56]:
# Find minimum and maximum values and their indexes:
print('Index for MINIMUM value:',tf.argmin(B).numpy())
print('MINIMUM value:',B[tf.argmin(B)].numpy())
print('Index for MAXIMUM value:',tf.argmax(B).numpy())
print('MAXIMUM value:',B[tf.argmax(B)].numpy())

Index for MINIMUM value: 1
MINIMUM value: 0
Index for MAXIMUM value: 5
MAXIMUM value: 9


In [57]:
B_OH = tf.one_hot(B, depth = 10)
B_OH

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]], dtype=float32)>

## 📖 Extra-curriculum

* Try to create a series of tensor functions to calculate your most recent grocery bill (it's okay if you don't use the names of the items, just the price in numerical form).
  * How would you calculate your grocery bill for the month and for the year using tensors?

In [64]:
# Create data:
products = tf.constant(
    ["Onions","Beef","Nuts","Detergent","Broom"]
)
prices = tf.constant([3.,20.,22.,10,30],dtype=tf.float16) # [$]
freq_per_month = tf.constant([10,8,3,2,0.25],dtype=tf.float16) # [per month]
products, prices, freq_per_month

(<tf.Tensor: shape=(5,), dtype=string, numpy=array([b'Onions', b'Beef', b'Nuts', b'Detergent', b'Broom'], dtype=object)>,
 <tf.Tensor: shape=(5,), dtype=float16, numpy=array([ 3., 20., 22., 10., 30.], dtype=float16)>,
 <tf.Tensor: shape=(5,), dtype=float16, numpy=array([10.  ,  8.  ,  3.  ,  2.  ,  0.25], dtype=float16)>)

In [70]:
tf.transpose(prices).shape,freq_per_month.shape

(TensorShape([5]), TensorShape([5]))

In [81]:
# Calculate bill per month:
print('Estimated bill per month: $',tf.tensordot(prices,freq_per_month,axes=1).numpy())

Estimated bill per month: $ 283.5
